### PR TITLE
updated eth-json-rpc-middleware on 4.4.0

### PR DESCRIPTION
**Pull request by logvik**
https://github.com/MetaMask/metamask-extension/issues/1190

### CODE REVIEW

**Comment by logvik** [comment]
@kumavis, please review these changes

**Review by Gudahtt — DISMISSED** [review]
It looks like a `yarn.lock` file got added somehow; that should be removed. This repository is still using `npm`.

**Comment by logvik** [comment]
@Gudahtt should I squash commits?

**Comment by Gudahtt** [comment]
Squashing is not required, as we can squash when the PR is merged.

**Review by whymarrh — APPROVED** [review]
I've rebased this on the latest, thanks @logvik!

**Pull request merged**
