### PR TITLE
Converting CI to GH actions

### PR DESCRIPTION
**Pull request by ryanml**
Related: https://github.com/MetaMask/MetaMask-planning/issues/32
- Added basic .editorconfig file

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM! Needs another push to run the actions though.

**Comment by ryanml** [comment]
@Gudahtt pushed

**Review by Gudahtt — APPROVED** [review]

**Comment by Gudahtt** [comment]
I've disabled status updates for this project on CircleCI now as well. Someone will still need to stop builds on CircleCI, but at least it won't annoy us with red X's in the meantime.

**Comment by Gudahtt** [comment]
I've disabled status updates for this project on CircleCI now as well. Someone will still need to stop builds on CircleCI, but at least it won't annoy us with red X's in the meantime.

**Pull request merged**
